### PR TITLE
Zero-Rotating Marker/Popup/Tooltip Pane

### PR DESCRIPTION
**Pull request by sisou**
This PR replaces #18 with a cleaned up commit history. It contains the same code as #18, just commited differently.

Please refer to the #18 thread for past discussion.

### CODE REVIEW

**Comment by fnicollet** [comment]
Hello @sisou, 
I gave your PR a try and the result is very good, it indeed fixes a couple issues like #8, and other weird behaviours. 

For instance, when you open a pop-up which doesn't fit on the screen, the map pans to give it enough space. With your version, the map pans properly, before it was doing some kind of weird diagonal move

There are still some stuff to figure out, but let's work from here

Thanks for your great work!
Fabien

**Comment by sisou** [comment]
Hey! 

Wow, awesome, I'm glad I could have such an impact on this wonderful library! 

I noticed the problem with the polyline disappearing on pan and zoom and reappearing on setBearing in the rotate.html example. It was there before this merge, too. I had a short look into it, but did not understand the structure of the files that handle polylines. 

What other issues are remaining, except a rebase onto the current main master branch (or v1.0.3 release)? Or do you mean the open issues on this repository?

**Comment by fnicollet** [comment]
Well the remaining issues are to me:
- Vector layers are not working so well
- Some bad behaviour on zoom 0/1 and rotated as the top-left corner is outside of the latlng bounds, which doesn't happen when not rotated
- Most importantly, Adapt to Leaflet > 1.0.3 #16 . 

I tried rebasing the main master branch but so much has changed, it's quite some work. Also, I'm not very familiar with the whole new ES6 stuff, but the namespaces have disappeared, so the merge is becoming a bit tricky, merge tools can't automatically merge the changes. It might be best cherry-picking the changes to:
https://github.com/Leaflet/Leaflet/tree/rotate

I am still unsure how to manage the two repositories, I like the fact that this repo has its own separate issues but it makes it hard to sync with the main master

A real merge will probably happen when rotation will be a priority for leaflet core, which is not the case right now

Fabien

**Comment by fnicollet** [comment]
A real merge will probably happen when rotation will be a priority for leaflet core, which is not the case right now

**Pull request merged**
